# Content for Antoine Bonhomme's portfolio site.
# Image references are (deck, hash-prefix) resolved against the extracted deck images.

SITE = {
    "name": "Antoine Bonhomme",
    "tagline": "Mechanical Engineering @ UC Berkeley",
    "email": "antoine.bonh@gmail.com",
    "phone": "858 280 1736",
    "linkedin": "https://www.linkedin.com/in/antoine-bonhomme-5b210a320/",
    "resume": "https://docs.google.com/document/d/1bYhJqDFZi9Dlk61fPpLYqg_OwdbEA28v_bysWaAPR18/edit?usp=sharing",
    "github": "https://github.com/AJBonhomme",
}

ABOUT = {
    "photo": ("main", "898d3a193f"),
    "paragraphs": [
        "Hi! I'm Antoine, a mechanical engineering student at UC Berkeley (B.S. expected 2028, GPA 3.95). I have a strong focus on autonomous robotics, hands-on system design, and real-world engineering projects — from retrofitting subsea robots to founding an autonomous racing team.",
        "My work spans the full loop: CAD and FEA in SolidWorks and Fusion 360, PCB design in KiCad, embedded control on ESP32 and Pixhawk, Python sensor APIs and controllers, and shop fabrication with MIG welding, plasma cutting and 3D printing.",
        "In my free time I love to work out (running, hitting the gym), cook, play video games (modded Kerbal Space Program), and hang out with friends.",
    ],
    "skills": {
        "Software & Design": "Python, Fusion 360, SolidWorks, Git, OpenCV, KiCad, FEA, PID Tuning",
        "Embedded & Sensors": "Raspberry Pi, ESP32, Pixhawk / ArduPilot, Doppler Velocity Log (DVL), Sonar, GPS, Computer Vision, Encoders",
        "Fabrication": "MIG Welding, Plasma Cutting, 3D Printing (PETG / ABS / TPU 95A), Laser Cutting, Soldering",
    },
    "experience": [
        ("Formula Electric at Berkeley", "Autonomous Systems & Powertrain Member", "Sep 2026 – Present"),
        ("SeeByte", "Mechanical Engineering Intern", "May 2026 – Aug 2026"),
        ("MesaFSD (Full Self-Driving) Club", "President & Founder", "May 2025 – May 2026"),
        ("UCSD DERConnect", "Research Assistant", "Jun 2025 – Aug 2025"),
        ("UCSD DERConnect", "Outreach Intern", "Nov 2024 – May 2025"),
    ],
    "gallery": [
        ("main", "cf83f7f4e1"), ("main", "4937468430"), ("main", "998c0b58dc"), ("main", "cb34d87fe1"),
    ],
}

# Each project: slug, title, year, cover, intro (list of paragraphs), sections (list of dicts)
# Section keys: heading (optional), text (list of paragraphs) or bullets (list), images (list of (deck, hash, caption)), layout ("stack" | "pair" | "triple")
PROJECTS = [
    {
        "slug": "feb-differential-mount",
        "title": "FEB Differential Mount",
        "year": "2026",
        "cover": ("feb_powertrain", "6115d4dbdd"),
        "subtitle": "Formula Electric at Berkeley — Powertrain",
        "intro": [
            "Designed a differential mounting assembly for Formula Electric at Berkeley's chain-driven rear drivetrain — an EMRAX 228 motor driving a Drexler FSAE differential through a 3.53:1 reduction. The assembly includes bearings, fasteners, frame tabs, a jacking bar and a chain tensioner, and was verified in SolidWorks FEA to a 1.5 minimum factor of safety under 4G shock loading.",
        ],
        "sections": [
            {"heading": "Requirements & Hand Calculations",
             "text": ["Started from the FSAE rules and the team's project brief: calculate the maximum load on the differential, mount it securely to the rear chassis with all required hardware, add a rules-compliant jacking bar, and compare chain-tensioning options (turnbuckle, eccentric, idler sprocket). From the motor's peak torque and the gear ratio I found the torque on the Drexler differential, then used the #40 chain and sprocket radius to convert that into an 8.4 kN tangential chain load on the mount."],
             "images": [("feb_powertrain", "7d09905f41", "FSAE rules envelope for the rear drivetrain"), ("feb_powertrain", "f758354045", "Motor peak torque → gear ratio → differential torque"), ("feb_powertrain", "854119f834", "Chain and sprocket hand calculations")],
             "layout": "triple"},
            {"heading": "Preliminary Sketches",
             "text": ["First sketches to envision the mount system before opening CAD — chain in pink, tabs in red, mount in blue, fasteners in green, bearings in purple. The idea: two mounting brackets cross-supported by a bar, mounted to the chassis via welded tabs, with tie rods used to adjust chain tension. These sketches were what I brought to office hours with senior team members."],
             "images": [("feb_powertrain", "86053cafaf", "Isometric concept sketch overlaid on the chassis"), ("feb_powertrain", "5d4ca6d56f", "Bracket concept"), ("feb_powertrain", "389f2e71f1", "Mount back view with support bar")],
             "layout": "triple"},
            {"heading": "SolidWorks Design",
             "text": ["Built two mounting brackets with fully defined sketches and repeatable dimensions — identical except for the bearing bore, since one side carries a smaller bearing. A bottom tooth mounts the jacking bar, and material was cut out of the bracket wherever it didn't carry load. The assembly was designed to minimize unique parts: 4× frame tabs, 2× tie rods, 80 mm and 90 mm brackets, a jack bar, and 4× M8 bolts with locknuts. Screwing the tie rods in or out moves the differential ±1 in for chain tension."],
             "images": [("feb_powertrain", "51cf80c65a", "Bracket drawing"), ("feb_powertrain", "927a67fdfe", "Bracket with bearing bore and jacking-bar tooth"), ("feb_powertrain", "f82ab06b08", "Full assembly on the rear chassis tubes")],
             "layout": "triple"},
            {"heading": "Simulation",
             "text": ["Tie rods were simplified as tabs of equivalent length, the tube chassis was used as the fixture, and all M8 hardware was modeled as bolted connections so hardware stress showed up in the results. Added the differential weight and the 8.4 kN chain force as remote loads, applied the weld tool to every welded item, assigned materials and generated the mesh."],
             "images": [("feb_powertrain", "71145f6413", "Remote loads applied where the chain acts"), ("feb_powertrain", "407e546e48", "Fixtures, connections and mesh")],
             "layout": "pair"},
            {"heading": "Analysis Results",
             "bullets": ["Applied an 8.4 kN chain load to the differential mount", "Maximum displacement of only about 0.22 mm", "Minimum factor of safety of 1.549 — meets the 1.5 target for this load case"],
             "images": [("feb_powertrain", "6a28562207", "Von Mises stress"), ("feb_powertrain", "1238a35f7a", "Factor of safety"), ("feb_powertrain", "71ecb63aa3", "Displacement")],
             "layout": "triple"},
            {"heading": "Materials, Cost & Manufacturing",
             "text": ["Chose AISI 4130 steel: strong and stiff enough for the differential and chain loads, easy to weld to the steel chassis and jacking bar, and low cost with room to remove material later. Tabs are laser or water cut and drilled, the jacking bar is chop-sawed, bearing bores and critical holes are CNC machined, and the final assembly is bolted and welded. Next steps: more FEA iterations to cut weight while keeping FOS near 1.5, more realistic contacts and load cases, and easier chain tensioning and differential removal."],
             "images": [("feb_powertrain", "eb247af870", "Final differential mount assembly")],
             "layout": "stack"},
        ],
    },
    {
        "slug": "feb-path-following-controller",
        "title": "FEB Path-Following Controller",
        "year": "2026",
        "cover": ("feb_autonomous", "4bce310200"),
        "subtitle": "Formula Electric at Berkeley — Autonomous",
        "intro": [
            "Developing a Python path-following controller for a simulated race car on a cone-defined track. The controller takes the vehicle state [x, y, heading φ, velocity v, steering angle θ] and outputs acceleration and steering-rate commands [a, θ̇], using a kinematic bicycle model and feedback control with steering and acceleration constraints. Objective: a fast, safe lap with no cones hit.",
        ],
        "sections": [
            {"heading": "Control Theory Learning",
             "text": ["Reviewed Python and NumPy array operations, learned vehicle state representation, studied the kinematic bicycle model, and worked through open-loop vs. closed-loop feedback and PID control — then applied each concept incrementally in the simulator."],
             "images": [("feb_autonomous", "99064adc19", "Kinematic bicycle model"), ("feb_autonomous", "45aa3097b6", "The cone-defined track and initial car pose"), ("feb_autonomous", "0a1834d225", "Feedback control notes")],
             "layout": "triple"},
            {"heading": "Learning Simulation",
             "text": ["Built a small timestep simulation to teach myself the fundamentals: start with a known state, apply a control, calculate the state derivatives, advance by dt, repeat. The first controller computed a desired heading toward a target with atan2 and used proportional feedback on the heading error — which worked, but caused the car to loop around the target with no way to correct lateral error."],
             "images": [("feb_autonomous", "4e1f65de98", "Spiralling into the target"), ("feb_autonomous", "8d5cb40b49", "Unstable gain"), ("feb_autonomous", "c37c0663ad", "Point-toward-target controller")],
             "layout": "triple"},
            {"heading": "From Target Tracking to Path Tracking",
             "text": ["Sampled the track centerline, found the closest centerline point to the car, computed the track direction and a signed lateral error (being 5 m away is not enough — you need to know which side of the track you're on), and combined it with heading error: θ̇ = K_heading · e_heading − K_lateral · e_lateral. Tuning the two gains is what keeps the car off the cones."],
             "images": [("feb_autonomous", "1be2eb8cdf", "Closest-point and lateral error"), ("feb_autonomous", "359e3ffcaf", "Early path tracking — oscillating around the centerline")],
             "layout": "pair"},
            {"heading": "Current P Controller",
             "text": ["The current controller follows the centerline cleanly around the full track. Next steps: better speed control, measuring lap time, and moving from a P controller to full PID."],
             "images": [("feb_autonomous", "0e6ad804e2", "Car trajectory vs. centerline"), ("feb_autonomous", "4bce310200", "Tuned heading + lateral controller")],
             "layout": "pair"},
        ],
    },
    {
        "slug": "seebyte-hovering-auv",
        "title": "SeeByte Hovering AUV Retrofit",
        "year": "2026",
        "cover": ("seebyte", "55bb0ecba4"),
        "subtitle": "Mechanical Engineering Intern · May – Aug 2026",
        "intro": [
            "Retrofitted two legacy Bluefin Hovering AUVs (HAUVs) — subsea robots built for autonomous dam-inspection missions that must hold precise heading, depth and position in high-current environments. I rebuilt their control stacks from the ground up: thrusters, a power distribution board and a tethered Ethernet comms link, plus Python APIs that fuse IMU, Doppler Velocity Log and depth-sensor data into a MAVLink-based flight controller for closed-loop dynamic positioning.",
            "Integrated a stereo camera and 3D sonar payload for underwater perception, tuned PID controllers to stable station-keeping validated in pool tests, integrated SeeByte's Neptune software for swarm control of three HAUVs, and authored the hardware, software and deployment documentation.",
        ],
        "sections": [
            {"heading": "The Vehicles",
             "images": [("seebyte", "734097b037", "The two HAUVs before retrofit"), ("seebyte", "cf83f7f4e1", "With the vehicle at the start of the internship"), ("seebyte", "4b4f409394", "HAUV CAD model")],
             "layout": "triple"},
            {"heading": "Engineering Process",
             "text": ["Applied a systems-engineering process to requirements, integration and testing, with a focus on simplicity for users. Test, test, test: bench test, unit test, integration test, system test. Each HAUV was fully deconstructed, keeping only the frame, thrusters and sensors; every thruster and sensor was unit tested, sub-assemblies (electronics enclosure, DVL and battery mount) were built and integration tested, then the vehicle was assembled, dry-land tested, and moved into the water."],
             "images": [("seebyte", "578e27cefb", "System electrical diagram, documented for future engineers"), ("seebyte", "7a5fb8e16b", "HAUV disassembled to hand sensors and thrusters over to unit testing")],
             "layout": "pair"},
            {"heading": "Sensor Unit Testing",
             "text": ["Unit tested every sensor to validate its working state, contacting manufacturers for SDKs to write custom Python scripts, and wrote a unit-test document for each one with wiring schematic, step-by-step plan, debugging steps and verification criteria. Sensors: Keller depth sensor, Teledyne DVL, Honeywell IMU, DIDSON sonar, DWE Stereo Explore 3D camera, and a Pixhawk Cube flight controller."],
             "images": [("seebyte", "4f470f9204", "Doppler Velocity Log"), ("seebyte", "3b376aa5e7", "DIDSON sonar"), ("seebyte", "7c086422ca", "Stereo 3D camera"), ("seebyte", "411a5b3e89", "Keller depth sensor"), ("seebyte", "c9c4f386f7", "Pixhawk Cube Orange"), ("seebyte", "a601df8baf", "Bench unit testing")],
             "layout": "triple"},
            {"heading": "Software — Sensor APIs",
             "text": ["For the Keller depth sensor I built a threaded read loop that polls pressure and temperature, converts pressure to depth (P = ρgh), validates the 0.5–40 bar range to reject bad readings, and shares timestamped samples across threads with a lock while tracking validity and staleness. For the DIDSON sonar I implemented its binary UDP protocol — building request packets matching the device byte layout, a two-stage header + 48-packet request flow, frame reassembly, and range extraction to the nearest object for obstacle detection, with socket timeouts for robustness."],
             "images": [("seebyte", "4f508b08ba", "Keller depth sensor API"), ("seebyte", "8fe93234bb", "DIDSON sonar UDP protocol")],
             "layout": "pair"},
            {"heading": "Electronics — Killswitch & Power Distribution",
             "text": ["Designed a killswitch for safety during testing and operation, and a power distribution board delivering unregulated power, 12 V (3 A / 10 A) and 5 V (3 A / 5 A) rails, built for modularity so future payloads can be added easily."],
             "images": [("seebyte", "df14c76874", "Killswitch wiring"), ("seebyte", "4c62d44393", "PDB schematic"), ("seebyte", "8f070598d0", "PDB layout, top and bottom")],
             "layout": "triple"},
            {"heading": "Hardware — Subsea End Cap",
             "text": ["Designed and dimensioned a multi-port subsea end cap for the pressure housing, laying out 19 SubConn bulkheads with BlueRobotics hardware, rated to 100 m depth and held to 1 mil tolerance. The larger bulkheads needed a nut on the back to get enough thread engagement (Lₑ ≥ 1D for full bolt strength, ≥ 0.75D minimum). Worked directly with the machinist for production, then integration and vacuum tested the finished cap for a watertight seal."],
             "images": [("seebyte", "66a62907fa", "End cap drawing"), ("seebyte", "1770ac9947", "Machined end cap with bulkheads installed"), ("seebyte", "a079746632", "Bulkhead layout in CAD")],
             "layout": "triple"},
            {"heading": "Hardware — Electronics Enclosure",
             "text": ["Designed modular trays to integrate ESCs, computers, sensors and power distribution into a seaworthy platform."],
             "images": [("seebyte", "833c7d7748", "Assembled electronics stack, top and bottom"), ("seebyte", "3fc85fdde9", "Full electronics assembly drawing"), ("seebyte", "4ceae8b7b5", "Tray assembly"), ("seebyte", "44568bc7fe", "Thread engagement cross-section")],
             "layout": "pair"},
            {"heading": "Water Testing & Autonomous Inspection",
             "text": ["Systems tested thrusters and sensors in the water, then demonstrated position hold and waypoint navigation. The autonomous dam-inspection behavior is a vertical lawn-mower survey of walls and pier pilings, with lane spacing defaulting to the stereo camera's field of view and a standoff distance set so cracks ≥ 125 cm long and ≥ 2 cm wide are reliably detected; the vehicle surfaces for a GPS fix on every ascent."],
             "images": [("seebyte", "6d09b796ef", "Water testing"), ("seebyte", "0a368624ce", "Mission planning"), ("seebyte", "a8daceb23d", "Vertical vs. horizontal survey plan")],
             "layout": "triple"},
            {"heading": "Documentation",
             "text": ["My team wrote hardware, software and deployment documentation, plus wiring and cable-routing schematics, so the project can keep growing after us."],
             "images": [("seebyte", "36965b18b2", "Electronic schematic"), ("seebyte", "5eb13a5c75", "End cap schematic")],
             "layout": "pair"},
        ],
    },
    {
        "slug": "mesafsd-autonomous-go-kart",
        "title": "MesaFSD Autonomous Go-Kart",
        "year": "2025",
        "cover": ("mesafsd", "7fb05a70fb"),
        "subtitle": "President & Founder · May 2025 – May 2026",
        "intro": [
            "Founded and led a 20-engineer multidisciplinary team at Mesa College to design and build an autonomous racing go-kart end-to-end, placing 5th nationally in the Autonomous Karting Series as a rookie team — and the only team out of nine to complete laps on its first race attempt.",
            "I designed the embedded control systems for autonomous actuation, integrating signal level-shifting and 5 V logic relays to drive 48 V solenoids and the brake master-cylinder pump; achieved an IP65 rating on a salvaged competition chassis by directing MIG-welding repairs and fabricating custom sealed enclosures; and secured $8,500 in funding plus $6,000 in student stipends through grants and sponsor pitches.",
        ],
        "sections": [
            {"heading": "Building the Team",
             "text": ["Gave speeches and presentations, tabled, led workshops and organized meetings to recruit and then educate members. Structured the club as an officer board plus Mechanical, Electrical and Software sub-team leads, with Marketing and Fundraising leads on the non-technical side. Met with each lead weekly for goal tracking and retention, and ran all tasks through Notion so status was visible to everyone."],
             "images": [("mesafsd", "aa232e9648", "The MesaFSD team at competition"), ("mesafsd", "c66fa6bdb8", "Notion task management for the software team"), ("mesafsd", "a331d5c5e9", "Team roster")],
             "layout": "triple"},
            {"heading": "Mechanical — Salvaged Chassis Repair",
             "text": ["TritonAI (UCSD's racing team) donated a crashed chassis. I built a decision matrix to compare a repair shop, a mentor, and an in-house repair, and the numbers favored doing it ourselves — lower cost and more learning value. Process: cut two notches to relieve stress, ratchet-strap the frame between a truck and a pole, pull it apart until it set, then re-weld the notches to solidify the chassis."],
             "images": [("mesafsd", "005cb859ec", "Bent chassis as received"), ("mesafsd", "04c0fcc807", "Crash-repair decision matrix"), ("mesafsd", "f0ee8262e2", "Straightened chassis"), ("mesafsd", "89a943e026", "MIG welding the repair")],
             "layout": "pair"},
            {"heading": "Mechanical — Enclosure Design",
             "text": ["Electronics had to live in IP65-rated boxes that fit all PDBs and computers, constrain every board and wire, stay easy to work on, and leave wall area for cable glands (plus 30% spare for wiring). Chose Polycase polycarbonate enclosures and laser-cut 1/8 in Delrin plates with hole arrays so sensors and boards could be re-arranged — modularity by design."],
             "images": [("mesafsd", "9070d910ed", "Layout sketch"), ("mesafsd", "5fa328718d", "Main computer enclosure in CAD"), ("mesafsd", "585849f941", "Laser-cut Delrin mounting plate")],
             "layout": "triple"},
            {"heading": "Electrical — Bench Prototype & System Diagram",
             "text": ["Validated the full control flow (QGroundControl → Cube → ESP32 → actuators) and the RC override path on the bench before touching the kart: verified the 48 / 24 / 12 / 5 V rails independently, confirmed RC to flight controller, checked low-level PWM to the Talon SRX steering and brake solenoid, fed GPS waypoints to simulate throttle and steering, and closed the steering loop with a REV through-bore encoder and software end-stops. The 48 V battery feeds a high-current PDB for the steering and throttle motors (15 A and 40 A+) and low-current PDBs the electrical team designed in KiCad; safety comes from a physical e-stop plus a remote kill solenoid."],
             "images": [("mesafsd", "d2efbc7967", "Table-top test of the autonomy stack"), ("mesafsd", "10134572aa", "Tier-1 MVP architecture"), ("mesafsd", "4a2d77bbd0", "Main electrical diagram"), ("mesafsd", "a8b46a96d8", "Low-current PDB")],
             "layout": "pair"},
            {"heading": "Software — ArduPilot on a Small Scale First",
             "text": ["Developed the autonomy on a smaller DonkeyCar first with a Pixhawk Cube Orange running ArduPilot and GPS waypoint navigation. The small car hosts the same sensors and software as the kart, so software, testing and operations could be developed in parallel while the kart was being built."],
             "images": [("mesafsd", "b290720c2b", "DonkeyCar test platform"), ("mesafsd", "9711564ca2", "GPS waypoint mission"), ("mesafsd", "0f38b4362f", "Mission Planner")],
             "layout": "triple"},
            {"heading": "Fundraising & Sponsors",
             "text": ["A new team with no money and no connections: we pitched tech and software companies, applied to the Mesa College Innovation Grant, ICC and ASG, and the Mesa Impactship Program. Result: over $8,500 raised for parts and over $6,000 in stipends to pay students. BrainCorp — a San Diego robotics-AI company with 40,000+ autonomous mobile robots deployed — became our first industry sponsor."],
             "images": [("mesafsd", "4e6edfaacb", "Visiting BrainCorp"), ("mesafsd", "87cb293070", "BrainCorp autonomous floor cleaner")],
             "layout": "pair"},
            {"heading": "Educating the Team",
             "text": ["Students learned electrical schematics, mechanical design and fabrication, software integration and the engineering design process through MonkeyBot — a project kit built from the ground up to teach every aspect of a robot — and DonkeyCar."],
             "images": [("mesafsd", "284db8acf4", "MonkeyBot"), ("mesafsd", "c618160bcb", "Build sessions"), ("mesafsd", "4edec44195", "Workshops")],
             "layout": "triple"},
            {"heading": "Competition",
             "text": ["Nine teams including Michigan, UCSD, UPenn, CU Boulder and Purdue. Rules: fully autonomous go-kart chassis, battery powered, all computation on the kart, full IP65 weatherproofing; five laps in under ten minutes, fastest time wins. We placed 5th, beating established teams, and were the only team to complete laps on the first attempt.",
                      "What I took away: isolate each issue to its smallest unit, validate it, then reintegrate. Make fast calls with incomplete information — a bad decision beats no decision. Choosing a conservative race strategy (lap stability over risky speed) was the difference between finishing 5th and finishing last. And we compensated for the bent chassis in software: power steering held the wheel centered via an encoder, correcting the mechanical bias in real time, with steering PIDs tuned track-side."],
             "images": [("mesafsd", "37a78c4c33", "Crossing the line autonomously"), ("mesafsd", "a20f007ba4", "Pit work between runs"), ("mesafsd", "e467345bd8", "Team and kart"), ("mesafsd", "ba91836330", "On track")],
             "layout": "pair"},
        ],
    },
    {
        "slug": "derconnect-microgrid-research",
        "title": "DERConnect Microgrid Research",
        "year": "2025",
        "cover": ("derconnect", "ad9945dda4"),
        "subtitle": "UCSD DERConnect Research Assistant · Jun – Aug 2025",
        "intro": [
            "Authored a microgrid-modeling paper — Preventative Feeder Overloading During DER System Failures in Residential Community Microgrids — using real-time hardware-in-the-loop simulation to keep neighborhood power grids from overloading when their solar and battery equipment suddenly fails. Published with Clean Coalition, a nonprofit energy organization.",
            "Also built out the DERConnect server room from scratch: 30+ compute nodes installed and configured, with custom laser-cut mounts and rack components for non-standard equipment.",
        ],
        "sections": [
            {"heading": "Staged Load Shedding",
             "text": ["The control strategy steps power use down in stages during an emergency. Stage I, adaptive prioritization: shed discretionary Tier-3 loads (EV charging, pool pumps, non-critical lighting), about 75% of demand, to stay under the feeder limit. Stage II, critical isolation: island the microgrid to serve only Tier-1 critical loads (~10% of normal demand). Stage III, emergency disconnect: trip all breakers so no surge reaches the feeder. Smart panels at each home execute the shedding autonomously, and 40 A emergency outlets stay powered through Stages II and III.",
                      "Because RSCAD only allows one output per variable, the stage selector is built from three switches with AND/NOT logic so only one can win at a time; the winner is multiplied by its shedding percentage to produce a single 0 / 10 / 50 / 70% signal fed to every home load block."],
             "images": [("derconnect", "ceb9cd6b26", "Research paper"), ("derconnect", "035314133e", "Stage-select logic in RSCAD"), ("derconnect", "3814c6406b", "Community microgrid draft model")],
             "layout": "triple"},
            {"heading": "Modeling, BESS Optimization & Testing",
             "text": ["Modeled the DOE Connected Community (Menifee, CA) in UC San Diego's Real-Time Digital Simulator using real 15-minute load profiles from campus buildings, compressing 24 hours into a 24-minute run with a Python downsampling script. Built a Python + CVX optimizer that schedules the 2 MW Li-ion battery's charge and discharge against variable pricing to cut cost and peak demand, with battery-health and spike penalties, linked it to the RTDS over Modbus, and validated it against disaster scenarios — BESS failure, PV failure, full grid loss — at peak-demand noon conditions."],
             "images": [("derconnect", "b8cf992895", "RSCAD runtime page"), ("derconnect", "6a8638e034", "24-minute compressed load data")],
             "layout": "pair"},
            {"heading": "Building the Server Room",
             "text": ["Installed and configured 30+ compute nodes for real-time grid simulation, designed and laser-cut custom mounting hardware for non-standard equipment, and handled the physical installation end-to-end — mounting, power and network cabling, and rack organization for airflow and serviceability — so the layout supports the lab's RTDS and hardware-in-the-loop workflows."],
             "images": [("derconnect", "10f2319fde", "Compute node"), ("derconnect", "ad9945dda4", "Rack build-out"), ("derconnect", "bce26dee04", "DERConnect research team")],
             "layout": "triple"},
        ],
    },
    {
        "slug": "derconnect-microgrid-pcb",
        "title": "Decentralized Microgrid PCB",
        "year": "2025",
        "cover": ("derconnect", "c718aeb75b"),
        "subtitle": "UCSD DERConnect Outreach Intern · Nov 2024 – May 2025",
        "intro": [
            "Designed a fully custom ESP32-based controller board for a decentralized residential microgrid with three power sources — solar, battery and utility grid — and islanding capability to disconnect and run autonomously during outages. Real-time energy-flow monitoring through a Hall-effect current sensor with an OLED for live status, smart load management that prioritizes critical loads and sheds non-critical ones, three independently switched consumer loads (Neighborhood, HVAC, EV) via MOSFETs, on-board 5 V regulation and diode-based power routing, all designed and 3D-rendered in KiCad.",
            "Along the way I built the microgrid up in stages with Arduino and ESP32 prototypes, gave a 30-minute technical talk on Distributed Energy Resources, and presented the demos in workshops for UCSD and Mesa College faculty.",
        ],
        "sections": [
            {"heading": "Final PCB",
             "images": [("derconnect", "c718aeb75b", "3D render of the controller board"), ("derconnect", "ff032b3965", "Schematic"), ("derconnect", "69957476db", "Layout in KiCad")],
             "layout": "triple"},
            {"heading": "Project 3 — Load Prioritization Controller",
             "text": ["Automatic power switching between battery and grid based on voltage: above 4 V the battery powers the critical load and contributes excess to the grid; between 2–4 V it powers the critical load only; at or below 2 V the grid takes over. Two relays route the critical load and battery-to-grid contribution, a MOSFET controls the non-critical load, and two voltage sensors monitor battery and grid. Grid instability turns the non-critical load off, with a 3-cycle debounce to avoid false triggers and fail-safe reverse relay logic."],
             "images": [("derconnect", "4292600ff8", "Circuit layout"), ("derconnect", "9f308951c6", "Breadboard build"), ("derconnect", "ec257c059c", "Controller code")],
             "layout": "triple"},
            {"heading": "Projects 1 & 2 — Solar Charging and Power Monitoring",
             "text": ["Project 1: a solar-powered battery charging system managed by an ESP32 with real-time voltage tracking and wireless control and logging through a web interface. Project 2: measuring AC current with an ACS712 sensor on the ESP32's 12-bit ADC, converting peak-to-peak voltage to RMS current and computing power."],
             "images": [("derconnect", "2a69bef734", "Solar charging prototype"), ("derconnect", "f4fd47b378", "Current measurement breadboard"), ("derconnect", "5f09e70211", "ESP32 wiring")],
             "layout": "triple"},
            {"heading": "Technical Talk — What Are DERs?",
             "text": ["A 30-minute presentation on Distributed Energy Resources and their role in grid resilience and efficiency, covering generation, storage and management, UC San Diego's campus-as-microgrid, and a Mesa College case study."],
             "images": [("derconnect", "8610e5507e", "Talk cover"), ("derconnect", "2ebd01d592", "Presenting"), ("derconnect", "27e4b9fec7", "Workshop session")],
             "layout": "triple"},
            {"heading": "Smart House IoT",
             "text": ["An Osoyoo Smart House kit built on Arduino — LEDs, motor, LCD, temperature/humidity and ultrasonic sensors, an RFID door lock — with WiFi added so the house can be controlled remotely from a phone."],
             "images": [("derconnect", "2e50afc5b5", "Smart house build"), ("derconnect", "ce120fdd12", "Interior wiring")],
             "layout": "pair"},
        ],
    },
    {
        "slug": "off-road-go-kart",
        "title": "Off-Road Go-Kart Build",
        "year": "2024",
        "cover": ("gokart", "9bf5b69b1d"),
        "subtitle": "Personal build · Sept 2023 – Jun 2024",
        "intro": [
            "Designed and fabricated a fully functional go-kart from scratch — braking, throttle, steering and drivetrain — over ten months, from first sketch to a rolling chassis with a 28 mph top speed. Modeled the frame and component geometry in Fusion 360 through 20 assembly revisions to resolve alignment and weld-joint tolerances, then cut, machined and MIG-welded the chassis using a plasma cutting table, grinders, drill press and saws.",
        ],
        "sections": [
            {"heading": "01 — Design",
             "text": ["Built the whole kart as a Fusion 360 assembly — chassis, spindles, tie rods, steering column, seat, wheels — so geometry problems showed up on screen instead of on the welding table. Locked wheelbase, track width and the driver package in the model, then pulled tube lengths and miter angles straight off it, with mounts for the battery box, control box and camera brackets."],
             "images": [("gokart", "7344136180", "GoKartFinalAssembly v20 — isometric"), ("gokart", "7805efc18c", "Side profile"), ("gokart", "6fd1857b0d", "Frame drawing")],
             "layout": "triple"},
            {"heading": "02 — Fabrication",
             "text": ["Cut square steel tube to length on the plasma table, then squared, deburred and finished every end. Laid the frame out flat, clamped and dry-fit each member before tacking, and re-cut wherever the real steel disagreed with the model — fitment, not cutting, was the hard part."],
             "images": [("main", "1d4fa5e760", "Plasma cutting table"), ("gokart", "f834f93d25", "Tube stock cut to length"), ("gokart", "1673261971", "Frame laid out flat")],
             "layout": "triple"},
            {"heading": "03 — Welding",
             "text": ["Ran practice beads on scrap coupons first, tuning wire speed and voltage until penetration and bead profile were consistent. Inspected every joint for undercut, porosity and cold lap — ground back and re-ran anything that didn't pass — and staggered welds around the frame to keep heat distortion from pulling it out of square. Every structural joint on the chassis is a MIG weld I laid, inspected and, when it needed it, cut out and ran again."],
             "images": [("gokart", "3cf2bcb8c0", "Practice coupon"), ("gokart", "b4fe4c6615", "Bead consistency"), ("main", "cb34d87fe1", "Welding the chassis")],
             "layout": "triple"},
            {"heading": "04 — Systems & Result",
             "text": ["Steering column, tie rods and spindles with geometry set in CAD; pedal-actuated brake and throttle packaged around the driver; a chain-and-sprocket drivetrain laid out around the rear axle; and seat, battery box and control box brackets bolted to the finished chassis. CAD gets you close, not done — fitment, heat distortion and tolerance stack-up all had to be solved with steel in hand."],
             "images": [("gokart", "86f0c6aa78", "Welded frame"), ("main", "fd85795d74", "Finished kart"), ("main", "975b063ed3", "28 mph top speed")],
             "layout": "triple"},
        ],
    },
    {
        "slug": "small-projects",
        "title": "Small Projects",
        "year": "2023 – 2024",
        "cover": ("personal", "b807b5969f"),
        "subtitle": "Arduino, 3D printing and self-taught electronics",
        "intro": [
            "Before the go-kart and the race team, there was a pile of small builds on a desk. I taught myself electronics and robotics from the ground up here — starting with an LED and a button, working up to a 3D-printed car that paths around obstacles on its own. Each one is small, but the progression is the point: every version failed at something specific, and the next one fixed it.",
        ],
        "sections": [
            {"heading": "Obstacle-Avoiding RC Car — v3",
             "text": ["The third version of a 3D-printed RC car I designed from scratch: a stronger roll cage on a tube-style frame to cut material cost, a front ultrasonic sensor and side IR sensors so the car paths around obstacles autonomously, and an OLED showing live sensor readings and the direction decision. Chassis designed in Autodesk Fusion and printed on a Bambu printer."],
             "images": [("personal", "74f8bdaa00", "v3 chassis in Fusion"), ("personal", "21c0426058", "Slicing for print"), ("personal", "e811326f3c", "Von Mises stress check on the cage")],
             "layout": "triple"},
            {"heading": "v3 — Avoidance Logic",
             "text": ["Sensors → check distance / IR → decision → motor action → repeat. Moves forward if the path is clear, stops and turns if an obstacle is near, and picks the clearest side. Detection range (15–30 cm) and turn speed are quick tweaks. Result: a strong roll cage and excellent obstacle avoidance, with fine tuning and rechargeable batteries next."],
             "images": [("personal", "2c34f9d18b", "v3 assembled and wired"), ("personal", "6c96d98cb6", "Setup and sensor pins"), ("personal", "d24e5d7e72", "Decision logic")],
             "layout": "triple"},
            {"heading": "v2 — Roll Cage",
             "text": ["Added a roll cage and condensed the chassis to lower material cost. Result: the cage was too weak and the body too narrow to fit the circuits inside — both fixed in v3."],
             "images": [("personal", "7cfa707ee6", "v2 chassis"), ("personal", "dd9df8230d", "Slicing"), ("personal", "b807b5969f", "Printed v2")],
             "layout": "triple"},
            {"heading": "v1 — Custom Chassis + OLED",
             "text": ["Redesigned the chassis for a better circuit layout, and added an OLED that shows the last direction command from the IR remote. It worked (with a weak IR signal) until an accidental 3 ft drop damaged the circuits."],
             "images": [("personal", "61e4880b5a", "v1 assembled"), ("personal", "b95449dc61", "v1 chassis in Fusion"), ("personal", "6b82f0cbcb", "IR remote control code")],
             "layout": "triple"},
            {"heading": "v0 — First Attempt & CAD Workshop",
             "text": ["A tutorial-sourced 3D-printed chassis with self-designed motor mounts. Didn't work — circuit error and insufficient power — but it started everything. A CAD workshop along the way covered sketching and extruding, measuring real parts with calipers, and building a rotating DC-motor wheel assembly."],
             "images": [("personal", "de3b9c85ef", "v0"), ("personal", "14c657e030", "Motor wheel assembly"), ("personal", "a07027ac22", "DC motor model")],
             "layout": "triple"},
            {"heading": "Handheld Distance Finder",
             "text": ["A handheld measuring device built from an Arduino, an ultrasonic sensor, a 16\u00d72 LCD and a battery, on a 3D-printed platform I designed to hold the circuits. The sensor fires a 10 \u00b5s pulse and the echo time converts to distance (cm = duration / 58, inches = duration / 148), updated every 100 ms on the LCD."],
             "images": [("personal", "5bde4fcb14", "Live readout"), ("personal", "1cf5c2c7ac", "Printed platform"), ("personal", "06719235b1", "Sketch")],
             "layout": "triple"},
            {"heading": "Arduino Training & Certifications",
             "text": ["Where it all started: button-controlled LEDs, a \u201cHello World \u2013 Antoine :)\u201d LCD with a potentiometer for contrast, and the basics of volts, current, resistors and switches. Completed the MATLAB, Simulink and Simscape OnRamp certifications along the way."],
             "images": [("personal", "5f13909470", "LCD hello world"), ("personal", "214a4e18db", "LED circuit"), ("personal", "8e8e8025d4", "First button circuit")],
             "layout": "triple"},
        ],
    },
]
